import unittest
from collections import OrderedDict
from context import woogenerator
from woogenerator.parsing.abstract import ImportObject

class TestObjList(unittest.TestCase):
    pass

class TestImportObject(unittest.TestCase):
    pass
    # def setUp(self):
        # Masters

    # slaves
    # args = (OrderedDict([('Tans Per Wk', ''),
    # ('MYOB Customer Card ID', ''),
    # ('GooglePlus Username', ''),
    # ('Home Address 2', ''),
    # ('Instagram Username', ''),
    # ('Added to mailing list', ''),
    # ('Edited in Wordpress', ''),
    # ('Address 2', ''),
    # ('Wordpress ID', u'1983'),
    # ('Twitter Username', ''),
    # ('Name Suffix', ''),
    # ('Middle Name', ''),
    # ('Contact', ''),
    # ('Name Prefix', ''),
    # ('Agent', ''),
    # ('Salutation', ''),
    # ('Shire', ''),
    # ('Lead Source', ''),
    # ('Spouse', ''),
    # ('Facebook Username', ''),
    # ('MYOB Card ID', u'C001280'),
    # ('E-mail', u'bdransfield2g@qq.com'),
    # ('Wordpress Username', u'bdransfield2g'),
    # ('Role', u'WN'),
    # ('First Name', u'Barn'),
    # ('Surname', u'Dransfield'),
    # ('Memo', u'\U0001f469\U0001f3fd'),
    # ('contact_schema', None),
    # ('schema', 'TT'),
    # ('source', 'WORDPRESS')]),)
    # kwargs = [('rowcount', 3),
    # ('row',
    # [u'C001280',
    # u'bdransfield2g@qq.com',
    # u'',
    # u'bdransfield2g',
    # u'1983',
    # u'WN',
    # u'Barn',
    # u'Dransfield',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'\U0001f469\U0001f3fd'])]
    #
    # args = (OrderedDict([('MYOB Card ID', u'C001280'),
    # ('Home Address 2', None),
    # ('Instagram Username', None),
    # ('Tans Per Wk', ''),
    # ('Added to mailing list', ''),
    # ('E-mail', u'bdransfield2g@qq.com'),
    # ('Shire', ''),
    # ('Middle Name', None),
    # ('Twitter Username', None),
    # ('source', 'WORDPRESS'),
    # ('Memo', None),
    # ('Address 2', None),
    # ('contact_schema', ''),
    # ('Wordpress Username', u'bdransfield2g'),
    # ('Name Prefix', None),
    # ('Spouse', ''),
    # ('schema', 'TT'),
    # ('GooglePlus Username', None),
    # ('Edited in Wordpress', ''),
    # ('Wordpress ID', u'1983'),
    # ('Name Suffix', None),
    # ('Lead Source', ''),
    # ('MYOB Customer Card ID', ''),
    # ('Surname', u'Dransfield'),
    # ('First Name', u'Barn'),
    # ('Agent', ''),
    # ('rowcount', 3),
    # ('Contact', None),
    # ('Facebook Username', None),
    # ('Salutation', ''),
    # ('Role', u'WN'),
    # ('Name', <woogenerator.contact_objects.ContactName object at 0x10c9a64d0>),
    # ('Address', <woogenerator.contact_objects.ContactAddress object at 0x10c9a6510>),
    # ('Home Address', <woogenerator.contact_objects.ContactAddress object at 0x10c9a6550>),
    # ('Phone Numbers', <woogenerator.contact_objects.ContactPhones object at 0x10c9a6590>),
    # ('Social Media', <woogenerator.contact_objects.SocialMediaFields object at 0x10c9a65d0>),
    # ('Role Info', <woogenerator.contact_objects.RoleGroup object at 0x10c9a6610>),
    # ('Personal E-mail', '')]),)
    # kwargs = [('rowcount', 3),
    # ('row',
    # [u'C001280',
    # u'bdransfield2g@qq.com',
    # u'',
    # u'bdransfield2g',
    # u'1983',
    # u'WN',
    # u'Barn',
    # u'Dransfield',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'',
    # u'\U0001f469\U0001f3fd'])]
    #
    # args = (OrderedDict([('City', u'Narutoch\u014d-mitsuishi'),
    # ('MYOB Card ID', u'C001280'),
    # ('Home Address 2', None),
    # ('Instagram Username', None),
    # ('schema', None),
    # ('Tans Per Wk', ''),
    # ('Added to mailing list', ''),
    # ('E-mail', u'lhayeb@wikia.com'),
    # ('Shire', ''),
    # ('Edited in Act', u'21/08/2013 8:10:55 AM'),
    # ('Mobile Phone Preferred', u'true'),
    # ('Middle Name', None),
    # ('Fax', u'02 5576 7738'),
    # ('Twitter Username', None),
    # ('Home Address 1', u'43 Miller Junction'),
    # ('Wordpress Start Date', u'2013-06-12 02:39:06'),
    # ('Edited Address', u'16/11/2015 11:06:24 PM'),
    # ('Address 1', u'68283 Monterey Lane'),
    # ('Memo', None),
    # ('Address 2', None),
    # ('contact_schema', 'act'),
    # ('Phone', u'02 1614 3894'),
    # ('Create Date', u'17/10/2009 7:42:01 AM'),
    # ('Name Prefix', None),
    # ('Home Country', u'RU'),
    # ('Edited Memo', u'28/12/2016 9:19:40 AM'),
    # ('Spouse', ''),
    # ('Home Postcode', u'692557'),
    # ('Last Sale', u'17/03/2016'),
    # ('GooglePlus Username', None),
    # ('Business Type', u'Advertising'),
    # ('Country', u'JP'),
    # ('Edited in Wordpress', ''),
    # ('Wordpress ID', ''),
    # ('Edited Spouse', u'3/06/2017 4:38:30 AM'),
    # ('ABN', u'47 862 859 335'),
    # ('Client Grade', u'Inactive 3yrs+'),
    # ('MYOB Customer Card ID', ''),
    # ('Contact', None),
    # ('Lead Source', ''),
    # ('Mobile Phone', u'0447 267 588'),
    # ('Edited Alt Address', u'2/05/2017 9:45:40 PM'),
    # ('Edited Company', u'13/01/2017 3:33:11 PM'),
    # ('Edited Personal E-mail', u'30/08/2015 1:25:53 PM'),
    # ('Edited Name', u'10/04/2016 3:32:56 PM'),
    # ('Direct Brand', u'VuTan Wholesale'),
    # ('Surname', u'Haye'),
    # ('Edited Phone Numbers', u'8/06/2016 11:24:07 AM'),
    # ('Postcode', u'779-0311'),
    # ('Edited Social Media', u'13/09/2016 9:50:32 PM'),
    # ('Agent', ''),
    # ('source', 'ACT'),
    # ('rowcount', 3),
    # ('Name Suffix', None),
    # ('Phone Preferred', u'true'),
    # ('Facebook Username', None),
    # ('Salutation', ''),
    # ('Role', u'WN'),
    # ('Home City', u'Novonikol\u2019sk'),
    # ('Company', u'Skinte'),
    # ('First Name', u'Lorry'),
    # ('Wordpress Username', ''),
    # ('Name', <woogenerator.contact_objects.ContactName object at 0x10c9a6150>),
    # ('Address', <woogenerator.contact_objects.ContactAddress object at 0x10c9a6210>),
    # ('Home Address', <woogenerator.contact_objects.ContactAddress object at 0x10c9a6110>),
    # ('Phone Numbers', <woogenerator.contact_objects.ContactPhones object at 0x10c9a6190>),
    # ('Social Media', <woogenerator.contact_objects.SocialMediaFields object at 0x10c9a6090>),
    # ('Role Info', <woogenerator.contact_objects.RoleGroup object at 0x10c9a6310>),
    # ('Personal E-mail', '')]),)
    # kwargs = [('rowcount', 3),
    # ('row',
    # [u'C001280',
    # u'lhayeb@wikia.com',
    # u'',
    # u'',
    # u'',
    # u'WN',
    # u'Lorry',
    # u'Haye',
    # u'Skinte',
    # u'0447 267 588',
    # u'02 1614 3894',
    # u'02 5576 7738',
    # u'true',
    # u'true',
    # u'68283 Monterey Lane',
    # u'Narutoch\u014d-mitsuishi',
    # u'779-0311',
    # u'',
    # u'JP',
    # u'43 Miller Junction',
    # u'Novonikol\u2019sk',
    # u'692557',
    # u'',
    # u'RU',
    # u'',
    # u'',
    # u'47 862 859 335',
    # u'Inactive 3yrs+',
    # u'VuTan Wholesale',
    # u'Advertising',
    # u'',
    # u'15/04/2016 5:13:03 PM',
    # u'10/04/2016 3:32:56 PM',
    # u'13/01/2017 3:33:11 PM',
    # u'8/06/2016 11:24:07 AM',
    # u'16/11/2015 11:06:24 PM',
    # u'2/05/2017 9:45:40 PM',
    # u'13/09/2016 9:50:32 PM',
    # u'19/01/2017 4:17:19 PM',
    # u'3/06/2017 4:38:30 AM',
    # u'28/12/2016 9:19:40 AM',
    # u'30/08/2015 1:25:53 PM',
    # u'',
    # u'17/10/2009 7:42:01 AM',
    # u'2013-06-12 02:39:06',
    # u'21/08/2013 8:10:55 AM',
    # u'17/03/2016',
    # u'\uff9f\uff65\u273f\u30fe\u2572(\uff61\u25d5\u203f\u25d5\uff61)\u2571\u273f\uff65\uff9f'])]
# TODO: Convert this to test cases

#
# if __name__ == '__main__':
#     in_dir = "../input/"
#     # act_path = os.path.join(in_dir, 'partial act records.csv')
#     act_path = os.path.join(in_dir, "500-act-records.csv")
#     out_dir = "../output/"
#     usr_path = os.path.join(out_dir, 'users.csv')
#
#     usrData = ColDataUser()
#
#     # print "import cols", usrData.get_import_cols()
#     # print "defaults", usrData.get_defaults()
#
#     usr_parser = CsvParseBase(
#         cols = usrData.get_import_cols(),
#         defaults = usrData.get_defaults()
#     )
#
#     usr_parser.analyse_file(act_path)
#
#     SanitationUtils.safe_print( usr_parser.tabulate(cols = usrData.get_report_cols()))
#     print ( usr_parser.tabulate(cols = usrData.get_report_cols()))
#
#     for usr in usr_parser.objects.values()[:3]:
#         pprint(OrderedDict(usr))
