from collections import OrderedDict

catReplace = OrderedDict([
	('Shimmerz for Hair', 'Tanning Accessories > Shimmerz for Hair'),
	('Generic Tanning Accessories', 'Tanning Accessories'),
	('Generic Technician Accessories', 'Technician Accessories'),
	('Sqiffy Accessories', 'Tanning Accessories > Sqiffy'),
	('Sticky Soul Accessories', 'Tanning Accessories'),
	# ('EzeBreathe', 'Tanning Accessories > EzeBreathe'),
	# ('My Tan', 'Tanning Accessories > My Tan'),
	# ('Tan Sleeper', 'Tanning Accessories > Tan Sleeper'),
	('Generic Application Equipment', 'Equipment > Application Equipment'),
	('Generic Tanning Booths', 'Equipment > Tanning Booths'),
	('Generic Literature', 'Marketing > Literature'),
	('Generic Signage', 'Marketing > Signage'),
	('Tanning Advantage Application Equipment', 'Equipment > Application Equipment'),
	
	('TechnoTan Solution', 'Solution'),
	('TechnoTan After Care', 'Tan Care > After Care'),
	('TechnoTan Pre Tan', 'Tan Care > Pre Tan'),
	('TechnoTan Tan Enhancement', 'Tan Care > Tan Enhancement'),
	('TechnoTan Hair Care', 'Tan Care > Hair Care'),
	('TechnoTan Tanning Accessories', 'Tanning Accessories'),
	('TechnoTan Technician Accessories', 'Technician Accessories'),
	('TechnoTan Application Equipment', 'Equipment > Application Equipment'),
	('TechnoTan Tanning Booths', 'Equipment > Tanning Booths'),
	('TechnoTan Apparel', 'Apparel'),
	('TechnoTan Literature', 'Marketing > Literature'),
	('TechnoTan Signage', 'Marketing > Signage'),
	('TechnoTan Spray Tanning Packages', 'Packages'),

	('VuTan Tanning Solution', 'Solution'),
	('VuTan Solution', 'Solution'),
	('VuTan After Care', 'Tan Care > After Care'),		
	('VuTan Pre Tan', 'Tan Care > Pre Tan'),
	('VuTan Tan Enhancement', 'Tan Care > Tan Enhancement'),
	('VuTan Hair Care', 'Tan Care > Hair Care'),
	('VuTan Tanning Booths', 'Equipment > Tanning Booths'),
	('VuTan Apparel', 'Apparel'),
	('VuTan Literature', 'Marketing > Literature'),
	('VuTan Signage', 'Marketing > Signage'),
	('VuTan Spray Tanning Packages', 'Packages'),
] )
colNames = OrderedDict([
	# ('product_type', ''),
	# ('upsell_skus', 'upsell_skus')
	# ('crosssell_skus', 'crosssell_skus'),
	('PA', ''),
	('VA', ''),
	('D', 'meta:wootan_danger'),
	('RNRC', 'meta:lc_rn_regular_price'),
	# ('WNRC', 'regular_price'),
	# ('RNS', '_sale_price'),
	('RPRC', 'meta:lc_rp_regular_price'),
	# ('RPS', 'meta:lc_rp_sale_price'),
	('WNRC', 'meta:lc_wn_regular_price'),
	# ('WNS', 'meta:lc_wn_sale_price'),
	('WPRC', 'meta:lc_wp_regular_price'),
	# ('WPS', 'meta:lc_wp_sale_price'),
	('DNRC', 'meta:lc_dn_regular_price'),
	# ('DNS', 'meta:lc_dn_sale_price'),
	('DPRC', 'meta:lc_dp_regulr_price'),
	# ('DPS', 'meta:lc_dp_sale_price'),
	('CVC', 'meta:commissionable_value'),
	('weight', 'weight'),
	('length', 'length'),
	('width', 'width'),
	('height', 'height'),
	('stock', 'stock'),
	('stock_status', 'stock_status'),
	('Images', ''),
	('imgsum', 'images'),
	('HTML Description', ''),
	('post_status', 'post_status'),
	# ('composition', 'composition'),
	# ('SKU lookup', 'meta:oldSKU'),
	('last_import', 'meta:last_import')
] )
defaults = OrderedDict( defaults.items() + [
	('CVC', 0),
	('post_status', 'publish'),
	('last_import', importName),
])
product_types = {
	'S': 'simple',
	'V': 'variable',
	'I': 'variable-instance',
	'C': 'composite',
	'G': 'grouped',
	'B': 'bundle',
}